@startditaa

  +--------+                 +-------+             +--------+   
  |        | <--WebSocket--> |       | --Consume-> |        |   
  | Client |                 |  AP   |             |RabbitMQ|   
  |        |                 |       |             |        |   
  |        |                 |       |             |        |   
  +---+----+                 +-------+             +--------+   
      |                                                ^   
      |                                                |   
      +------------------Publish-----------------------+   

@endditaa