spring:
  profiles:
    active: product
  freemarker:
    suffix: .ftl
    cache: false
    template-loader-path: classpath:/templates/
    expose-request-attributes: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
