spring:
  profiles:
    active: live
  freemarker:
    suffix: .ftl
    cache: false
    template-loader-path: classpath:/templates/
    expose-request-attributes: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
debug: true
google:
  api:
    key: "AIzaSyBote7e630I7WkqFUUY9GjbT20fIPiUdmI"
  vision:
    key: ${google.api.key}
  recaptcha:
    site: "6Lc8bwImAAAAAHnng3IjN3iPf2K1rLKFdYQYb_w8"
    secret: "6Lc8bwImAAAAAIf2sqKos_sfnnLmHeIVo9NtFcpL"

