@startuml
salt
{+
[回列表]
  帳號   | "                         "
  姓名   | "                         "
  密碼   | "                         "
  密碼確認| "                         "
  性別   | {()男 | (X)女}
  生日   | "109/01/02<&calendar>"
  E-mail| "                         "
  是否驗證信箱| {()是 | (X)否}
  是否停用| {[X]是}

  {
     [修改]
  }
}
@enduml