spring:
  profiles:
    active: product
  freemarker:
    suffix: .ftl
    cache: false
    template-loader-path: classpath:/templates/
    expose-request-attributes: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2
google:
  api:
    key: ${GOOGLE_API_KEY}
  vision:
    key: ${google.api.key}
  recaptcha:
    site: ${RECAPTCHA_SITE}
    secret: ${RECAPTCHA_SECRET}
  oauth:
    id: ${GOOGLE_OAUTH_ID}
    secret: ${GOOGLE_OAUTH_SECRET}
oauth:
  id: client
  secret: password
oas:
  owner: 許嵩業
  mail: kido6115@gmail.com
line:
  oauth:
    id: ${LINE_OAUTH_ID}
    secret: ${LINE_OAUTH_SECRET}
debug: false
