logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
debug: true
google:
  oauth:
    redirect: "http://localhost:8080/google/openid"
line:
  oauth:
    redirect: "http://localhost:8080/line/openid"
