spring:
  profiles:
    active: product
  freemarker:
    suffix: .ftl
    cache: false
    template-loader-path: classpath:/templates/
    expose-request-attributes: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
google:
  api:
    key: "AIzaSyBote7e630I7WkqFUUY9GjbT20fIPiUdmI"
  vision:
    key: ${google.api.key}
  recaptcha:
    site: "6Lc8bwImAAAAAHnng3IjN3iPf2K1rLKFdYQYb_w8"
    secret: "6Lc8bwImAAAAAIf2sqKos_sfnnLmHeIVo9NtFcpL"
  oauth:
    id: "329193090490-5phkddntmnd815q9edcurgr4tc92csfs.apps.googleusercontent.com"
    secret: "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"
line:
  oauth:
    id: "1661142035"
    secret: "91a042d425a12f11ee99bc67b4cc2190"
oauth:
  id: client
  secret: password
