google:
  oauth:
    redirect: "https://spring-boot-series-4vuktvrsua-de.a.run.app/google/openid"
line:
  oauth:
    redirect: "https://spring-boot-series-4vuktvrsua-de.a.run.app/line/openid"
  server: "https://line-4vuktvrsua-de.a.run.app"
oauth:
  authorization-server: "https://authorization-server-4vuktvrsua-de.a.run.app"
  authorization-endpoint: "https://authorization-server-4vuktvrsua-de.a.run.app/oauth2/token"
  redirect: "https://spring-boot-series-4vuktvrsua-de.a.run.app/oauth/openid"
system:
  url: "https://spring-boot-series-4vuktvrsua-de.a.run.app"
oas:
  url: ${system.url}
